version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: gw-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./app/backend
    image: gw-backend:latest
    container_name: gw-backend
    env_file:
      - .env
    environment:
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-1.5-pro}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CORS_ALLOW_ORIGINS=*
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./app/backend:/srv

  frontend:
    build:
      context: ./app/frontend
    image: gw-frontend:latest
    container_name: gw-frontend
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  redis_data:
